/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/scene.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.932, 0, -1.513]} rotation={[Math.PI, -1.562, Math.PI]}>
        <mesh geometry={nodes.Cube001_Cube002_BlackCoatSteel.geometry} material={materials.BlackCoatSteel} />
        <mesh geometry={nodes.Cube001_Cube002_BlackCoatSteel_1.geometry} material={materials.GrayPlastic} />
        <mesh geometry={nodes.Cube001_Cube002_BlackCoatSteel_2.geometry} material={materials.WhiteSteelScrew} />
        <mesh geometry={nodes.Cube001_Cube002_BlackCoatSteel_3.geometry} material={materials.BlackPlastic} />
        <mesh geometry={nodes.Cube001_Cube002_BlackCoatSteel_4.geometry} material={materials.BlackWood} />
      </group>
      <mesh geometry={nodes.rug.geometry} material={materials.phong1SG} position={[0.032, 0, 0.54]} rotation={[0, -0.003, 0]} />
      <group position={[0.81, 0, -1.077]} rotation={[-Math.PI / 2, 0, -3.115]}>
        <mesh geometry={nodes.OfficeChair_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.OfficeChair_2.geometry} material={materials.Black} />
        <mesh geometry={nodes.OfficeChair_3.geometry} material={materials.Chair} />
      </group>
      <group position={[1.739, 1.313, -1.61]} rotation={[-Math.PI, 1.563, -Math.PI]}>
        <mesh geometry={nodes.mesh549538436.geometry} material={materials.mat23} />
        <mesh geometry={nodes.mesh549538436_1.geometry} material={materials.mat8} />
        <mesh geometry={nodes.mesh549538436_2.geometry} material={materials.mat24} />
        <mesh geometry={nodes.mesh549538436_3.geometry} material={materials.mat17} />
        <mesh geometry={nodes.mesh549538436_4.geometry} material={materials.mat16} />
        <mesh geometry={nodes.mesh549538436_5.geometry} material={materials.mat21} />
        <mesh geometry={nodes.mesh549538436_6.geometry} material={materials.mat3} />
        <mesh geometry={nodes.mesh549538436_7.geometry} material={materials.mat10} />
        <mesh geometry={nodes.mesh549538436_8.geometry} material={materials.mat9} />
        <mesh geometry={nodes.mesh549538436_9.geometry} material={materials.mat15} />
        <mesh geometry={nodes.mesh549538436_10.geometry} material={materials.mat22} />
        <mesh geometry={nodes.mesh549538436_11.geometry} material={materials.mat11} />
        <mesh geometry={nodes.mesh549538436_12.geometry} material={materials.mat12} />
        <mesh geometry={nodes.mesh549538436_13.geometry} material={materials.mat5} />
        <mesh geometry={nodes.mesh549538436_14.geometry} material={materials.mat13} />
        <mesh geometry={nodes.mesh549538436_15.geometry} material={materials.mat2} />
      </group>
      <mesh geometry={nodes.Monitor.geometry} material={materials.Mat} position={[1.208, 0.943, -1.828]} rotation={[0, 1.217, 0]} />
      <mesh geometry={nodes.Mouse.geometry} material={materials['Material.001']} position={[1.256, 0.943, -1.217]} />
      <mesh geometry={nodes.Keyboard1.geometry} material={materials.lambert3SG} position={[0.812, 0.941, -1.195]} />
      <group position={[-2.212, 2.382, -0.126]} rotation={[0, 0.826, 0]}>
        <mesh geometry={nodes.mesh2044496107.geometry} material={materials['mat21.001']} />
        <mesh geometry={nodes.mesh2044496107_1.geometry} material={materials['mat8.001']} />
        <mesh geometry={nodes.mesh2044496107_2.geometry} material={materials['mat3.001']} />
        <mesh geometry={nodes.mesh2044496107_3.geometry} material={materials['mat23.001']} />
        <mesh geometry={nodes.mesh2044496107_4.geometry} material={materials['mat15.001']} />
        <mesh geometry={nodes.mesh2044496107_5.geometry} material={materials['mat2.001']} />
        <mesh geometry={nodes.mesh2044496107_6.geometry} material={materials['mat24.001']} />
        <mesh geometry={nodes.mesh2044496107_7.geometry} material={materials['mat12.001']} />
        <mesh geometry={nodes.mesh2044496107_8.geometry} material={materials['mat16.001']} />
        <mesh geometry={nodes.mesh2044496107_9.geometry} material={materials.mat0} />
        <mesh geometry={nodes.mesh2044496107_10.geometry} material={materials['mat9.001']} />
        <mesh geometry={nodes.mesh2044496107_11.geometry} material={materials['mat17.001']} />
        <mesh geometry={nodes.mesh2044496107_12.geometry} material={materials['mat10.001']} />
        <mesh geometry={nodes.mesh2044496107_13.geometry} material={materials.mat14} />
        <mesh geometry={nodes.mesh2044496107_14.geometry} material={materials['mat13.001']} />
      </group>
      <mesh geometry={nodes.Shelf.geometry} material={materials.FFCC88} position={[-0.786, 1.682, -1.987]} />
      <group position={[-1.319, 2.051, -1.841]} rotation={[3.114, -0.306, 3.055]}>
        <mesh geometry={nodes.mesh184873240.geometry} material={materials['mat8.002']} />
        <mesh geometry={nodes.mesh184873240_1.geometry} material={materials['mat23.002']} />
        <mesh geometry={nodes.mesh184873240_2.geometry} material={materials['mat17.002']} />
      </group>
      <mesh geometry={nodes.CoffePlant_mehs.geometry} material={materials['CoffeePlant_mat.001']} position={[-1.797, 0, 1.741]} rotation={[Math.PI, -1.54, Math.PI]} />
      <group position={[-0.304, 2.261, -1.919]} rotation={[Math.PI, -0.128, Math.PI]}>
        <mesh geometry={nodes.mesh20059432.geometry} material={materials['mat3.002']} />
        <mesh geometry={nodes.mesh20059432_1.geometry} material={materials['mat12.002']} />
        <mesh geometry={nodes.mesh20059432_2.geometry} material={materials['mat8.003']} />
        <mesh geometry={nodes.mesh20059432_3.geometry} material={materials['mat21.002']} />
        <mesh geometry={nodes.mesh20059432_4.geometry} material={materials['mat5.001']} />
        <mesh geometry={nodes.mesh20059432_5.geometry} material={materials['mat9.002']} />
        <mesh geometry={nodes.mesh20059432_6.geometry} material={materials['mat23.003']} />
        <mesh geometry={nodes.mesh20059432_7.geometry} material={materials['mat16.002']} />
        <mesh geometry={nodes.mesh20059432_8.geometry} material={materials['mat13.002']} />
      </group>
      <group position={[-0.823, 2.205, -1.989]} rotation={[Math.PI, -0.016, Math.PI]}>
        <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh'].geometry} material={materials['1A1A1A']} />
        <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_1'].geometry} material={materials.DD9944} />
        <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_2'].geometry} material={materials.F44336} />
        <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_3'].geometry} material={materials.FFFFFF} />
        <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_4'].geometry} material={materials['039BE5']} />
        <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_5'].geometry} material={materials['795548']} />
        <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_6'].geometry} material={materials['00BCD4']} />
        <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_7'].geometry} material={materials['FFCC88.001']} />
        <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_8'].geometry} material={materials['009688']} />
      </group>
      <mesh geometry={nodes.Mug_with_office_tools.geometry} material={materials['Material.003']} position={[0.041, 0.942, -1.569]} />
      <mesh geometry={nodes.ElectricGuitar_mesh.geometry} material={materials.lambert2SG} position={[0.536, 1.856, -1.96]} rotation={[0, 0, -0.884]} />
      <mesh geometry={nodes.piano.geometry} material={materials.palette} position={[1.652, 0.942, -0.846]} />
      <group position={[-0.318, 0, 0.483]} rotation={[-Math.PI, 0.001, -Math.PI]}>
        <mesh geometry={nodes.mic001_1.geometry} material={materials['Black.001']} />
        <mesh geometry={nodes.mic001_2.geometry} material={materials.Metal} />
        <mesh geometry={nodes.mic001_3.geometry} material={materials.Glow} />
        <mesh geometry={nodes.mic001_4.geometry} material={materials.LightGrey} />
      </group>
      <mesh geometry={nodes.Monitor001.geometry} material={materials['Mat.001']} position={[0.428, 0.943, -1.825]} rotation={[-Math.PI, 1.225, -Math.PI]} />
      <group position={[-1.721, 1.388, -1.721]} rotation={[1.926, -0.393, -2.372]}>
        <mesh geometry={nodes.Mesh003.geometry} material={materials.black} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials.L_yellow} />
        <mesh geometry={nodes.Mesh003_2.geometry} material={materials.white} />
        <mesh geometry={nodes.Mesh003_3.geometry} material={materials.brown} />
      </group>
      <mesh geometry={nodes['Mur-1'].geometry} material={materials['brick-wall.001']} />
      <mesh geometry={nodes['Mur-2'].geometry} material={materials['wall.001']} />
      <mesh geometry={nodes.Mouse001.geometry} material={materials['Material.005']} position={[1.256, 0.943, -1.217]} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials['parquet sombre']} />
      <mesh geometry={nodes.Plane_2.geometry} material={materials['wall.001']} />
    </group>
  )
}

useGLTF.preload('/scene.glb')
